### ISSUE TITLE
Responses to descriptive questions are not saved

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#13]
I cannot find any of the answers to the descriptive questions from the survey analysis page.

**Comment by debajyotiGuha** [comment]
This problem is fixed. Updated, please check once.

**Comment by rikalively** [comment]
Where can I find where they saved? Both of these pictures are from the analyze survey page - the graph says their are answers but the other widget says there were none. Is it saving the text from the question? There needs to be a way to find what users had typed in for that question rather than just keeping the number of answers.

<img width="275" alt="screen shot 2016-11-07 at 8 59 17 am" src="https://cloud.githubusercontent.com/assets/23104131/20060334/bbcd4004-a4c8-11e6-9059-5d452261d9dc.png">

<img width="1088" alt="screen shot 2016-11-07 at 8 59 07 am" src="https://cloud.githubusercontent.com/assets/23104131/20060308/9995eb1c-a4c8-11e6-84eb-2e41e1a6476f.png">

**Comment by debajyotiGuha** [comment]
Please refresh the site with cache clear or just press ctrl+f5 and test one more time. I have checked it in with Dawn Hammond account and it's working fine.

**Comment by rikalively** [comment]
Where are you finding the answers to the descriptive questions? I'm still getting the same results after refreshing and clearing cache.

**Comment by debajyotiGuha** [comment]
OK, I got the scenario where this problem occurred. There is some problem in storing in the first question answered. That because of the user structure. Till date this survey works for maximum one response for a person per day. But because it need to store more than one response for a person for same day it will take whole up-gradation in survey structure. So once I completed the user and organization structure I start working on this. And need to discuss with @bikash02  sir and @debdiproy sir about the time estimation and proper process.

**Comment by rikalively** [comment]
Okay - thank you @debajyotiGuha

**Comment by rikalively** [comment]
How are we doing with this issue?

**Comment by debajyotiGuha** [comment]
It will resolved shortly.

**Comment by Designer-cleonix** [comment]
@debajyotiGuha what is the update?

**Comment by debajyotiGuha** [comment]
This has resolved. Please check once.

**Comment by rikalively** [comment]
Working now. Thank you!
